# Generated by Django 3.2.15 on 2022-10-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=12)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roupacama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntd', models.IntegerField()),
                ('tamanho', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=300)),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=30)),
                ('qntd', models.IntegerField()),
                ('tamanho', models.CharField(max_length=3)),
                ('desc', models.CharField(max_length=300)),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Higiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300)),
                ('qntd', models.IntegerField()),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntd', models.FloatField()),
                ('vencimento', models.DateField()),
                ('desc', models.CharField(max_length=300)),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto')),
            ],
        ),
    ]
