# Generated by Django 4.1.2 on 2022-10-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_alimento_desc_remove_alimento_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dt_ingresso', models.DateField(null=True)),
                ('dt_nasct', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('telefone', models.CharField(max_length=12, null=True)),
                ('cep', models.CharField(max_length=15, null=True)),
                ('endereco', models.CharField(max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='roupa',
            old_name='descr',
            new_name='tipos',
        ),
        migrations.RemoveField(
            model_name='higiene',
            name='condicao',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='alimento',
            name='tipos',
            field=models.CharField(choices=[('1', 'Carboidrato'), ('2', 'sei la'), ('3', 'Pasta de dentes'), ('4', 'Papel Higiênico')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='higiene',
            name='tipos',
            field=models.CharField(choices=[('1', 'Sabonete'), ('2', 'Escova de dentes'), ('3', 'Pasta de dentes'), ('4', 'Papel Higiênico')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='integrante',
            name='dt_ingresso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='integrante',
            name='dt_nasct',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='integrante',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roupacama',
            name='condicao',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AddField(
            model_name='roupacama',
            name='cor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='roupacama',
            name='tipos',
            field=models.CharField(choices=[('1', 'Lençol'), ('2', 'Cobertor'), ('3', 'Fronha'), ('4', 'sei la')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='descr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='higiene',
            name='descr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='tamanho',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='roupacama',
            name='descr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='roupacama',
            name='tamanho',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casal', 'Casal'), ('QueenSize', 'QueenSize'), ('KingSize', 'KingSize')], max_length=10, null=True),
        ),
    ]
