# Generated by Django 4.1.2 on 2022-11-01 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0003_funcionario_rename_descr_roupa_tipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='tipos',
            field=models.CharField(choices=[('Carboidrato', 'Carboidrato'), ('Leite', 'Leite'), ('Oléo', 'Oléo'), ('Acucar', 'Acucar')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='higiene',
            name='tipos',
            field=models.CharField(choices=[('Sabonete', 'Sabonete'), ('Escoava de dentes', 'Escova de dentes'), ('Pasta de dentes', 'Pasta de dentes'), ('Papel Higiênico', 'Papel Higiênico')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='condicao',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='tipos',
            field=models.CharField(choices=[('Calça', 'Calça'), ('Casaco', 'Casaco'), ('Camiseta', 'Camiseta'), ('Camisa', 'Camisa')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='roupacama',
            name='condicao',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='roupacama',
            name='tipos',
            field=models.CharField(choices=[('Lençol', 'Lençol'), ('Cobertor', 'Cobertor'), ('Fronha', 'Fronha'), ('4', 'sei la')], max_length=30, null=True),
        ),
    ]
