# Generated by Django 4.1.2 on 2022-11-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
