# Generated by Django 4.1.2 on 2022-11-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='senha',
        ),
    ]
